name: developerFunnel Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: ['22.12.0]


    
